# Generated by Django 5.0.4 on 2024-05-03 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
