# Generated by Django 5.0.4 on 2024-05-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usercart_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='custom_img',
            field=models.ImageField(default=None, null=True, upload_to='orders/images/'),
        ),
    ]
