# Generated by Django 5.0.4 on 2024-05-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usercart_custom_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='custom_img',
            field=models.ImageField(null=True, upload_to='orders/images/'),
        ),
    ]
