# Generated by Django 5.0.4 on 2024-05-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_city_user_phone_number_addres_order_shipping_addres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='shipping_charges',
            field=models.FloatField(default=0.0),
        ),
    ]
