# Generated by Django 5.0.4 on 2024-05-13 06:21

import api.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_city_shipping_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('uses', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('deadline', models.DateField(default=api.models.get_default_expiry)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promo_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocodes'),
        ),
        migrations.CreateModel(
            name='UserPromoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.promocodes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
