# Generated by Django 5.0.4 on 2024-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='product_size',
            field=models.CharField(default='s', max_length=5),
            preserve_default=False,
        ),
    ]
