# Generated by Django 5.0.4 on 2024-05-16 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_producttype_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='size',
            field=models.CharField(default='small', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='defaults/product_def.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='starting',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
