# Generated by Django 5.0.4 on 2024-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_producttype_product_size_orderedproduct_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
