# Generated by Django 5.0.4 on 2024-07-01 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_designtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.designtype'),
            preserve_default=False,
        ),
    ]
