# Generated by Django 5.0.4 on 2024-07-01 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_design_design_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='designs/shirt_styles/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='custom_img',
        ),
        migrations.CreateModel(
            name='OrderedDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.ImageField(null=True, upload_to='orders/images/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('shirt_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shirtstyle')),
            ],
        ),
        migrations.CreateModel(
            name='UserDesignCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(max_length=10)),
                ('image', models.ImageField(default=None, null=True, upload_to='orders/images/')),
                ('shirt_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shirtstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
