# Generated by Django 5.0.4 on 2024-07-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_usercart_custom_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='custom_img',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='custom_img',
        ),
    ]
