# Generated by Django 5.0.4 on 2024-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_ordereddesign_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercustomcart',
            name='image',
            field=models.FileField(upload_to='custom/images/'),
        ),
    ]
