# Generated by Django 5.0.4 on 2024-07-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_order_payment_id_alter_usercustomcart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedcustom',
            name='order',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereddesign',
            name='order',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
            preserve_default=False,
        ),
    ]
