# Generated by Django 5.0.4 on 2024-07-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_orderedcustom_order_ordereddesign_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedcustom',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordereddesign',
            name='user',
        ),
    ]
