# Generated by Django 5.0.4 on 2024-07-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_orderedcustom_user_remove_ordereddesign_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedcustom',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
