# Generated by Django 5.0.4 on 2024-07-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_orderedcustom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomcart',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
