from django.urls import path
from . import views

urlpatterns = [
      path("auth/<str:code>/", views.LoginApi.as_view(), name="login-with-google"),
      path("auth/", views.LoginApi.as_view(), name="login-withought-google"),
      path("whoami/", views.WhoAmI.as_view(), name="Who-Am-I"),
      path("logout/", views.Logout.as_view(), name="Logout"),
      path('verify-email/<str:uidb64>/<str:token>/', views.VerifyEmail.as_view(), name='verify-email'),
      path("address/", views.AddressView.as_view()),
      path("city/", views.CityView.as_view()),
      path("product_type/", views.ProductTypeView.as_view()),
      path("add_product/", views.AddProducts.as_view()),
      path("update_product/<int:id>/", views.ChangeProduct.as_view()),
      path("get_product/", views.GetProducts.as_view()),
      path("get_product_details/<int:id>", views.GetProductDetails.as_view()),
      path("upload_product_images/<int:id>", views.UploadProductImage.as_view()),
      path("shirt_styles/", views.ShirtStyleView.as_view()),
      path("design_type/", views.DesignTypeView.as_view()),
      path("add_design/", views.AddDesigns.as_view()),
      path("get_design/", views.GetDesigns.as_view()),
      path("get_custom_product/", views.GetCustomProduct.as_view()),
      path('task_status/<str:task_id>/', views.TaskStatus.as_view(), name='task_status'),
      path("cart/", views.Cart.as_view()),
      path('design_cart/', views.UserDesignCartView.as_view(), name='user_design_cart'),
      path('custom_cart/', views.UserCustomCartView.as_view(), name='user_custom_cart'),
      path("delete_cart_item/<int:id>/<str:type>", views.DeleteCartItem.as_view()),
      path("update_cart_product_quantity/<str:item>/<int:id>/<str:action>", views.UpdateCartQuantity.as_view()),
      path("create_checkout_session/", views.CreateCheckoutSession.as_view()),
      path("confirm_checkout/<int:order_id>", views.ConfirmCheckout.as_view()),
      path("confirm_transaction/", views.TransactionView.as_view()),
      path("cancel_order/<int:order_id>", views.CancelOrder.as_view()),
      path("get_all_orders/", views.GetAllOrders.as_view()),
      path("get_my_orders/", views.GetMyOrders.as_view()),
      path("get_this_order/<int:order_id>", views.GetThisOrder.as_view()),
      #path("promo/<str:code>/", views.PromoView.as_view(),name="promo"),
      path("promo/", views.PromoView.as_view(),name="promo"),
      path("users/", views.UserApi.as_view()),
      path("update_city/<int:id>",views.UpdatecityApi.as_view()),
      path("delete_city/<int:id>",views.DeletecityApi.as_view()),

]